# =============================================================================
# ATLAS CONDA ENVIRONMENT (CPU-ONLY)
# =============================================================================
# This file defines a stable, CPU-only environment for running the ATLAS
# pipelines. It is the recommended setup for users without an NVIDIA GPU.
#
# To create this environment, run:
#   conda env create -f environment-cpu.yml
#
# =============================================================================
name: atlas-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  # Core scientific stack
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - biopython
  - scipy
  - tqdm

  # For R&D and visualization
  - jupyterlab
  - matplotlib
  - seaborn

  # For the "Explorer" pipeline (future)
  - gensim
  - hdbscan

  # TensorFlow (CPU version)
  # This version is optimized for CPU and does not require CUDA/cuDNN.
  - tensorflow-cpu
